function initFishingFishConfig() {
	setup.fishingFish = {
		haddock: {
			minSize: 35,
			maxSize: 90,
			preferredSeason: ["autumn"],
			preferredTime: ["dusk"],
			preferredLocation: ["pier"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			maxStamina: 4,
			locations: {
				pier: 0.5,
				coastPath: 0.5,
			},
			icon: "fish/haddock.png",
		},
		salmon: {
			minSize: 45,
			maxSize: 120,
			preferredSeason: ["autumn"],
			preferredTime: ["dawn"],
			preferredLocation: ["forestLake", "coastPath", "pier"],
			preferredWeather: ["lightClouds", "storm", "thunderstorm"],
			maxStamina: 5,
			locations: {
				pier: 1,
				coastPath: 1,
				forestLake: 0.5,
			},
			icon: "fish/salmon.png",
		},
		trout: {
			minSize: 25,
			maxSize: 80,
			preferredSeason: ["spring"],
			preferredTime: ["dawn"],
			preferredLocation: ["forestLake"],
			preferredWeather: ["clear", "storm", "thunderstorm"],
			maxStamina: 3,
			locations: {
				forestLake: 1,
				moor: 1,
			},
			icon: "fish/trout.png",
		},
		cod: {
			minSize: 40,
			maxSize: 140,
			preferredSeason: ["winter"],
			preferredTime: ["dusk"],
			preferredLocation: ["coastPath"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			maxStamina: 5,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/cod.png",
		},
		herring: {
			minSize: 20,
			maxSize: 45,
			preferredSeason: ["autumn", "winter"],
			preferredTime: ["dawn"],
			preferredLocation: ["beach", "pier"],
			preferredWeather: ["lightClouds", "heavyClouds", "storm"],
			maxStamina: 2,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 0.5,
			},
			icon: "fish/herring.png",
		},
		whiting: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["winter"],
			preferredTime: ["dusk", "night"],
			preferredLocation: ["pier", "coastPath"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			maxStamina: 3,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/whiting.png",
		},
		mackerel: {
			minSize: 22,
			maxSize: 50,
			preferredSeason: ["summer"],
			preferredTime: ["dawn", "day"],
			preferredLocation: ["beach", "coastPath"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			maxStamina: 3,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/mackerel.png",
		},
		flounder: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["spring", "summer"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["beach", "coastPath"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			maxStamina: 3,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/flounder.png",
		},
		sole: {
			minSize: 24,
			maxSize: 65,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["night", "dusk"],
			preferredLocation: ["pier", "coastPath"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			maxStamina: 4,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/sole.png",
		},
		bass: {
			minSize: 35,
			maxSize: 95,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["pier", "coastPath"],
			preferredWeather: ["clear", "lightClouds", "storm"],
			maxStamina: 5,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/bass.png",
		},
		roach: {
			minSize: 15,
			maxSize: 45,
			preferredSeason: ["spring", "summer"],
			preferredTime: ["day", "dawn"],
			preferredLocation: ["forestLake", "moor"],
			preferredWeather: ["clear", "lightClouds", "lightPrecipitation"],
			maxStamina: 2,
			locations: {
				forestLake: 1,
				moor: 0.5,
			},
			icon: "fish/roach.png",
		},
		perch: {
			minSize: 20,
			maxSize: 60,
			preferredSeason: ["autumn"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["forestLake", "moor"],
			preferredWeather: ["lightClouds", "heavyClouds", "lightPrecipitation"],
			maxStamina: 3,
			locations: {
				forestLake: 1,
				moor: 1,
			},
			icon: "fish/perch.png",
		},
		chub: {
			minSize: 25,
			maxSize: 80,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["day", "dusk"],
			preferredLocation: ["forestLake", "moor"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			maxStamina: 4,
			locations: {
				forestLake: 0.5,
				moor: 0.25,
			},
			icon: "fish/chub.png",
		},
		pike: {
			minSize: 45,
			maxSize: 130,
			preferredSeason: ["autumn", "winter"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["forestLake", "moor"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			maxStamina: 6,
			locations: {
				forestLake: 1,
				moor: 0.75,
			},
			icon: "fish/pike.png",
		},
		eel: {
			minSize: 35,
			maxSize: 110,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["night", "dusk"],
			preferredLocation: ["forestLake", "moor"],
			preferredWeather: ["heavyClouds", "lightPrecipitation", "storm", "thunderstorm"],
			maxStamina: 6,
			locations: {
				forestLake: 1,
				moor: 0.5,
			},
			icon: "fish/eel.png",
		},
		grayling: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["winter"],
			preferredTime: ["day", "dawn"],
			preferredLocation: ["forestLake"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			maxStamina: 4,
			locations: {
				forestLake: 0.25,
			},
			icon: "fish/grayling.png",
		},
	};
}
window.initFishingFishConfig = initFishingFishConfig;
