function initFishingFishConfig() {
	setup.fishing_fish = {
		haddock: {
			min_size: 35,
			max_size: 90,
			preferred_season: ["autumn"],
			preferred_time: ["dusk"],
			preferred_location: ["pier"],
			preferred_weather: ["heavyClouds", "storm", "thunderstorm"],
			max_stamina: 4,
			locations: {
				pier: 0.5,
				coastPath: 0.5,
			},
			icon: "fish/haddock.png",
		},
		salmon: {
			min_size: 45,
			max_size: 120,
			preferred_season: ["autumn"],
			preferred_time: ["dawn"],
			preferred_location: ["forestLake", "coastPath", "pier"],
			preferred_weather: ["lightClouds", "storm", "thunderstorm"],
			max_stamina: 5,
			locations: {
				pier: 1,
				coastPath: 1,
				forestLake: 0.5,
			},
			icon: "fish/salmon.png",
		},
		trout: {
			min_size: 25,
			max_size: 80,
			preferred_season: ["spring"],
			preferred_time: ["dawn"],
			preferred_location: ["forestLake"],
			preferred_weather: ["clear", "storm", "thunderstorm"],
			max_stamina: 3,
			locations: {
				forestLake: 1,
				moor: 1,
			},
			icon: "fish/trout.png",
		},
		cod: {
			min_size: 40,
			max_size: 140,
			preferred_season: ["winter"],
			preferred_time: ["dusk"],
			preferred_location: ["coastPath"],
			preferred_weather: ["heavyClouds", "storm", "thunderstorm"],
			max_stamina: 5,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/cod.png",
		},
		herring: {
			min_size: 20,
			max_size: 45,
			preferred_season: ["autumn", "winter"],
			preferred_time: ["dawn"],
			preferred_location: ["beach", "pier"],
			preferred_weather: ["lightClouds", "heavyClouds", "storm"],
			max_stamina: 2,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 0.5,
			},
			icon: "fish/herring.png",
		},
		whiting: {
			min_size: 25,
			max_size: 60,
			preferred_season: ["winter"],
			preferred_time: ["dusk", "night"],
			preferred_location: ["pier", "coastPath"],
			preferred_weather: ["heavyClouds", "storm", "thunderstorm"],
			max_stamina: 3,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/whiting.png",
		},
		mackerel: {
			min_size: 22,
			max_size: 50,
			preferred_season: ["summer"],
			preferred_time: ["dawn", "day"],
			preferred_location: ["beach", "coastPath"],
			preferred_weather: ["clear", "lightClouds", "heavyClouds"],
			max_stamina: 3,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/mackerel.png",
		},
		flounder: {
			min_size: 25,
			max_size: 60,
			preferred_season: ["spring", "summer"],
			preferred_time: ["dawn", "dusk"],
			preferred_location: ["beach", "coastPath"],
			preferred_weather: ["clear", "lightClouds", "heavyClouds"],
			max_stamina: 3,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/flounder.png",
		},
		sole: {
			min_size: 24,
			max_size: 65,
			preferred_season: ["summer", "autumn"],
			preferred_time: ["night", "dusk"],
			preferred_location: ["pier", "coastPath"],
			preferred_weather: ["heavyClouds", "storm", "thunderstorm"],
			max_stamina: 4,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/sole.png",
		},
		bass: {
			min_size: 35,
			max_size: 95,
			preferred_season: ["summer", "autumn"],
			preferred_time: ["dawn", "dusk"],
			preferred_location: ["pier", "coastPath"],
			preferred_weather: ["clear", "lightClouds", "storm"],
			max_stamina: 5,
			locations: {
				beach: 1,
				pier: 1,
				coastPath: 1,
			},
			icon: "fish/bass.png",
		},
		roach: {
			min_size: 15,
			max_size: 45,
			preferred_season: ["spring", "summer"],
			preferred_time: ["day", "dawn"],
			preferred_location: ["forestLake", "moor"],
			preferred_weather: ["clear", "lightClouds", "lightPrecipitation"],
			max_stamina: 2,
			locations: {
				forestLake: 1,
				moor: 0.5,
			},
			icon: "fish/roach.png",
		},
		perch: {
			min_size: 20,
			max_size: 60,
			preferred_season: ["autumn"],
			preferred_time: ["dawn", "dusk"],
			preferred_location: ["forestLake", "moor"],
			preferred_weather: ["lightClouds", "heavyClouds", "lightPrecipitation"],
			max_stamina: 3,
			locations: {
				forestLake: 1,
				moor: 1,
			},
			icon: "fish/perch.png",
		},
		chub: {
			min_size: 25,
			max_size: 80,
			preferred_season: ["summer", "autumn"],
			preferred_time: ["day", "dusk"],
			preferred_location: ["forestLake", "moor"],
			preferred_weather: ["clear", "lightClouds", "heavyClouds"],
			max_stamina: 4,
			locations: {
				forestLake: 0.5,
				moor: 0.25,
			},
			icon: "fish/chub.png",
		},
		pike: {
			min_size: 45,
			max_size: 130,
			preferred_season: ["autumn", "winter"],
			preferred_time: ["dawn", "dusk"],
			preferred_location: ["forestLake", "moor"],
			preferred_weather: ["heavyClouds", "storm", "thunderstorm"],
			max_stamina: 6,
			locations: {
				forestLake: 1,
				moor: 0.75,
			},
			icon: "fish/pike.png",
		},
		eel: {
			min_size: 35,
			max_size: 110,
			preferred_season: ["summer", "autumn"],
			preferred_time: ["night", "dusk"],
			preferred_location: ["forestLake", "moor"],
			preferred_weather: ["heavyClouds", "lightPrecipitation", "storm", "thunderstorm"],
			max_stamina: 6,
			locations: {
				forestLake: 1,
				moor: 0.5,
			},
			icon: "fish/eel.png",
		},
		grayling: {
			min_size: 25,
			max_size: 60,
			preferred_season: ["winter"],
			preferred_time: ["day", "dawn"],
			preferred_location: ["forestLake"],
			preferred_weather: ["clear", "lightClouds", "heavyClouds"],
			max_stamina: 4,
			locations: {
				forestLake: 0.25,
			},
			icon: "fish/grayling.png",
		},
	};
}
window.initFishingFishConfig = initFishingFishConfig;
