function initFishingFishConfig() {
	setup.fishing = { lootTables: {} };
	setup.fishing.lootTables.fish = {
		haddock: {
			minSize: 35,
			maxSize: 90,
			preferredSeason: ["autumn"],
			preferredTime: ["dusk"],
			preferredLocation: ["fishingPier"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			locations: {
				fishingPier: 0.5,
				fishingCoastPath: 0.5,
			},
			cookable: true,
			icon: "fish/haddock.png",
		},
		salmon: {
			minSize: 45,
			maxSize: 120,
			preferredSeason: ["autumn"],
			preferredTime: ["dawn"],
			preferredLocation: ["fishingForestLake", "fishingCoastPath", "fishingPier"],
			preferredWeather: ["lightClouds", "storm", "thunderstorm"],
			locations: {
				fishingPier: 1,
				fishingCoastPath: 1,
				fishingForestLake: 0.5,
			},
			cookable: true,
			icon: "fish/salmon.png",
		},
		trout: {
			minSize: 25,
			maxSize: 80,
			preferredSeason: ["spring"],
			preferredTime: ["dawn"],
			preferredLocation: ["fishingForestLake"],
			preferredWeather: ["clear", "storm", "thunderstorm"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 1,
			},
			cookable: true,
			icon: "fish/trout.png",
		},
		cod: {
			minSize: 40,
			maxSize: 140,
			preferredSeason: ["winter"],
			preferredTime: ["dusk"],
			preferredLocation: ["fishingCoastPath"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: true,
			icon: "fish/cod.png",
		},
		herring: {
			minSize: 20,
			maxSize: 45,
			preferredSeason: ["autumn", "winter"],
			preferredTime: ["dawn"],
			preferredLocation: ["fishingBeach", "fishingPier"],
			preferredWeather: ["lightClouds", "heavyClouds", "storm"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 0.5,
			},
			cookable: false,
			icon: "fish/herring.png",
		},
		whiting: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["winter"],
			preferredTime: ["dusk", "night"],
			preferredLocation: ["fishingPier", "fishingCoastPath"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			icon: "fish/whiting.png",
		},
		mackerel: {
			minSize: 22,
			maxSize: 50,
			preferredSeason: ["summer"],
			preferredTime: ["dawn", "day"],
			preferredLocation: ["fishingBeach", "fishingCoastPath"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			icon: "fish/mackerel.png",
		},
		flounder: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["spring", "summer"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["fishingBeach", "fishingCoastPath"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			icon: "fish/flounder.png",
		},
		sole: {
			minSize: 24,
			maxSize: 65,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["night", "dusk"],
			preferredLocation: ["fishingPier", "fishingCoastPath"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: false,
			icon: "fish/sole.png",
		},
		bass: {
			minSize: 35,
			maxSize: 95,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["fishingPier", "fishingCoastPath"],
			preferredWeather: ["clear", "lightClouds", "storm"],
			locations: {
				fishingBeach: 1,
				fishingPier: 1,
				fishingCoastPath: 1,
			},
			cookable: true,
			icon: "fish/bass.png",
		},
		roach: {
			minSize: 15,
			maxSize: 45,
			preferredSeason: ["spring", "summer"],
			preferredTime: ["day", "dawn"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			preferredWeather: ["clear", "lightClouds", "lightPrecipitation"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 0.5,
			},
			cookable: false,
			icon: "fish/roach.png",
		},
		perch: {
			minSize: 20,
			maxSize: 60,
			preferredSeason: ["autumn"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			preferredWeather: ["lightClouds", "heavyClouds", "lightPrecipitation"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 1,
			},
			cookable: true,
			icon: "fish/perch.png",
		},
		chub: {
			minSize: 25,
			maxSize: 80,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["day", "dusk"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			locations: {
				fishingForestLake: 0.5,
				fishingMoor: 0.25,
			},
			cookable: true,
			icon: "fish/chub.png",
		},
		pike: {
			minSize: 45,
			maxSize: 130,
			preferredSeason: ["autumn", "winter"],
			preferredTime: ["dawn", "dusk"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			preferredWeather: ["heavyClouds", "storm", "thunderstorm"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 0.75,
			},
			cookable: true,
			icon: "fish/pike.png",
		},
		eel: {
			minSize: 35,
			maxSize: 110,
			preferredSeason: ["summer", "autumn"],
			preferredTime: ["night", "dusk"],
			preferredLocation: ["fishingForestLake", "fishingMoor"],
			preferredWeather: ["heavyClouds", "lightPrecipitation", "storm", "thunderstorm"],
			locations: {
				fishingForestLake: 1,
				fishingMoor: 0.5,
			},
			cookable: false,
			icon: "fish/eel.png",
		},
		grayling: {
			minSize: 25,
			maxSize: 60,
			preferredSeason: ["winter"],
			preferredTime: ["day", "dawn"],
			preferredLocation: ["fishingForestLake"],
			preferredWeather: ["clear", "lightClouds", "heavyClouds"],
			locations: {
				fishingForestLake: 0.25,
			},
			cookable: false,
			icon: "fish/grayling.png",
		},
	};

	setup.fishing.reelFightMinSize = 80;

	setup.fishing.lootTables.magnetScrap = {
		horseshoe: { name: "old horseshoe", value: 3, weight: 2 },
		numberPlate: { name: "bent number plate", value: 2, weight: 2 },
		kitchenKnife: { name: "kitchen knife", value: 6, weight: 2 },
		padlock: { name: "heavy steel padlock", value: 5, weight: 2 },
		toolbox: { name: "rusted toolbox", value: 24, weight: 1, locations: ["fishingBeach", "fishingPier", "fishingMoor"] },
		leadDivingWeight: { name: "lead diving weight", value: 9, weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath", "fishingMoor"] },
		bentCopperPipe: { name: "bent copper pipe", value: 12, weight: 0.75, locations: ["fishingBeach", "fishingPier", "fishingCoastPath", "fishingMoor"] },
		copperWireBundle: { name: "clump of copper wire", value: 16, weight: 0.5, locations: ["fishingBeach", "fishingPier", "fishingMoor"] },
		screwdriver: { name: "old screwdriver", value: 4, weight: 1.5, locations: ["fishingPier", "fishingMoor"] },
		forceps: { name: "rusted forceps", value: 6, weight: 1, locations: ["fishingPier", "fishingMoor"] },
		drillBits: { name: "handful of drill bits", value: 3, weight: 1, locations: ["fishingPier", "fishingMoor"] },
		pliers: { name: "pair of pliers", value: 4, weight: 1.5, locations: ["fishingPier", "fishingMoor"] },
		silverCutlery: { name: "set of silver cutlery", value: 25, weight: 0.5, locations: ["fishingMoor"] },
		chainLength: { name: "length of old chain", value: 6, big: true },
		shoppingTrolley: { name: "shopping trolley", value: 10, big: true },
		boatAnchor: { name: "barnacled boat anchor", value: 25, big: true },
		oldBicycle: { name: "rust-eaten bicycle", value: 10, big: true },
		shovel: { name: "rusted shovel", value: 5, big: true },
		cashRegister: { name: "old cash register", value: 40, big: true },
		cannonball: { name: "iron cannonball", value: 40, big: true },
	};

	setup.fishing.lootTables.fishingTrash = {
		boot: { weight: 1, isLitter: true },
		plasticBag: { weight: 1.5, isLitter: true },

		fishingLine: { weight: 1, isLitter: true },
		netting: { weight: 0.75, isLitter: true },
		seaweed: { weight: 1.5, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		conchShell: { weight: 0.75, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		mussel: { weight: 1, isLitter: false, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		driftwood: { weight: 1, isLitter: false },
		pondweed: { weight: 1.5, isLitter: false, locations: ["fishingForestLake", "fishingMoor"] },
	};

	setup.fishing.lootTables.fishingClothing = {
		"bikini top": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"bikini bottoms": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"board shorts": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"swim shirt": { weight: 1, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"School swim top": { weight: 0.5, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"School swim bottoms": { weight: 0.5, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
		"Swimming goggles": { weight: 0.5, locations: ["fishingBeach", "fishingPier", "fishingCoastPath"] },
	};
}
window.initFishingFishConfig = initFishingFishConfig;
