// THIS FILE IS AUTOGENERATED
// DO NOT EDIT ORIGINAL TEXT
// You CAN add comments ABOVE filepath
// You CAN delete WARNINGS if you are sure
// that translation IS CORRECT
Object.assign(setup.i18n["ru-RU"], {
	// base-system/text.twee:638
	// base-system-text-pronouns-he
	"text-2a279fc3": "",

	// base-system/text.twee:640
	// base-system-text-pronouns-she
	"text-ca9f911a": "",

	// base-system/text.twee:642
	// base-system-text-pronouns-it
	"text-c90f958e": "",

	// base-system/text.twee:644
	// base-system-text-pronouns-one
	"text-538c30b1": "",

	// base-system/text.twee:646
	// base-system-text-pronouns-they
	"text-626a6172": "",
});
