// THIS FILE IS AUTOGENERATED
// DO NOT EDIT ORIGINAL TEXT
// You CAN add comments ABOVE filepath
// You CAN delete WARNINGS if you are sure
// that translation IS CORRECT
Object.assign(setup.i18n["ru-RU"], {
	// 01-config/start.twee:62
	// Welcome to the alpha of Degrees of Lewdity!
	"start-6e6f3444": "",

	// 01-config/start.twee:65
	// If you want to avoid trouble, <span class="gold">keep your allure low</span> by dressing modestly and sticking to safe, well-lit areas. Nights are particularly dangerous. Dressing lewd will attract attention, both good and bad, and the more vulnerable you look, the more danger you are in. Be careful!
	"start-f1c85163": "",

	// 01-config/start.twee:71
	// The school year starts on the first Monday of January at <<ampm 9 0>>. The bus service is the easiest way to get around town. Don't forget your uniform and backpack!
	"start-347568c4": "",

	// 01-config/start.twee:73
	// School starts tomorrow at <<ampm 9 0>>. The bus service is the easiest way to get around town. Don't forget your uniform and backpack!
	"start-86f8beea": "",

	// 01-config/start.twee:75
	// The new school year starts tomorrow at <<ampm 9 00>>. The bus service is the easiest way to get around town. Don't forget your uniform and backpack!
	"start-4824f77a": "",

	// 01-config/start.twee:81
	// <<link [[Next|Orphanage Intro]]>><</link>>
	"start-b80082b5": "",
});
